INSERT INTO books (title, author, published_in, genre, pages_count, description) VALUES
     ('The Wandering Light', 'Alice Greenwood', 2005, 'Fantasy', 342, 'An epic journey across magical realms.'),
     ('Silent Echoes', 'Daniel Storm', 2011, 'Mystery', 289, 'A detective follows whispers through abandoned streets.'),
     ('Beyond the Veil', 'Maria Huxley', 2018, 'Thriller', 412, 'Secrets behind the curtain of a corrupt society.'),
     ('The Art of Stillness', 'John Pearson', 2020, 'Philosophy', 174, 'A reflection on the power of quiet living.'),
     ('Chasing the Horizon', 'Lily Martins', 2002, 'Adventure', 321, 'Sailing to the edge of the known world.'),
     ('Code of Silence', 'Ethan Moore', 2015, 'Techno-thriller', 399, 'Hackers uncover dangerous digital secrets.'),
     ('Shadows in Time', 'Rachel Geller', 1998, 'Science Fiction', 278, 'Time travelers risk it all to stop a paradox.'),
     ('Midnight Confessions', 'Sophia Reyes', 2013, 'Romance', 235, 'Love letters and long-distance heartache.'),
     ('Fragments of Us', 'Leo Carter', 2016, 'Drama', 198, 'A tale of memory, identity, and healing.'),
     ('Echoes from the Past', 'Grace Lin', 2009, 'Historical', 361, 'A family secret uncovered across generations.'),
     ('Digital Ashes', 'Ken Bradley', 2021, 'Sci-Fi', 310, 'A.I. rebellion in a fractured future.'),
     ('Glass Hearts', 'Emily Cruz', 2007, 'Romance', 223, 'Two strangers, one broken past.'),
     ('The Fire Keeper', 'Owen Hale', 2019, 'Fantasy', 382, 'A cursed child born of flame.'),
     ('The Quiet Rebellion', 'Samantha Blake', 2010, 'Historical Fiction', 337, 'Resistance grows in unexpected silence.'),
     ('The Clockmaker''s Paradox', 'Elliot Quinn', 2022, 'Sci-Fi', 400, 'A scientist trapped in his own invention.'),
     ('Letters to Nowhere', 'Monica Wells', 2003, 'Drama', 259, 'Letters that never found their home.'),
     ('The Golden Thread', 'Harper Dean', 2014, 'Mythology', 341, 'A journey through ancient myths.'),
     ('Dreamless Sleep', 'Victor James', 2006, 'Horror', 198, 'When the nightmares never stop.'),
     ('Tides of Tomorrow', 'Isla Monroe', 2017, 'Science Fiction', 312, 'Earth’s last hope is hidden beneath the waves.'),
     ('The Architect''s Code', 'Brandon Ross', 2012, 'Thriller', 280, 'Blueprints with deadly consequences.'),
     ('Rust and Stardust', 'Megan Hall', 2018, 'Romance', 297, 'Love between artists in a decaying city.'),
     ('Crimson Harvest', 'Dean Foster', 2004, 'Horror', 301, 'A cursed village and the coming of blood moon.'),
     ('Neon Memories', 'Jade Winters', 2020, 'Cyberpunk', 368, 'Memories for sale in the neon underworld.'),
     ('Stormborn', 'Natalie Rivers', 2001, 'Fantasy', 349, 'A warrior princess and a fallen kingdom.'),
     ('Beneath Cold Skies', 'Craig Daniels', 2015, 'Drama', 244, 'A family lost to war and winter.'),
     ('The Hollow Sun', 'Ingrid Vaughn', 2008, 'Science Fiction', 289, 'A colony fights for light on a dying star.'),
     ('Of Smoke and Bone', 'Thomas Ray', 2013, 'Fantasy', 367, 'Forbidden magic resurfaces in a crumbling empire.'),
     ('Paper Castles', 'Elena Brooks', 2010, 'Romance', 221, 'Fragile love built on shaky dreams.'),
     ('The Last Monolith', 'Jordan Cole', 2016, 'Adventure', 430, 'A race to uncover ancient power.'),
     ('Veins of the Earth', 'Lucia Stone', 2019, 'Environmental Fiction', 299, 'Nature’s wrath awakens underground.'),
     ('Winter''s Edge', 'Arthur Blake', 2005, 'Mystery', 287, 'Murder in a remote alpine town.'),
     ('Dust and Silence', 'Nina Grey', 2007, 'Post-Apocalyptic', 321, 'Survivors cling to hope in the wasteland.'),
     ('Inkbound', 'Harvey King', 2011, 'Fantasy', 358, 'A magical library that rewrites destiny.'),
     ('The Mirage Labyrinth', 'Carmen Fox', 2014, 'Adventure', 276, 'A lost explorer’s clues to a shifting maze.'),
     ('The Hollow Verse', 'Oliver Chase', 2023, 'Poetry', 150, 'Dark poetry from the edge of sanity.'),
     ('Whispers of Avalon', 'Tanya Fields', 2002, 'Mythology', 330, 'Legends rise with the mists.'),
     ('The Plastic Sky', 'Zane Dalton', 2006, 'Sci-Fi', 370, 'Earth’s atmosphere has turned synthetic.'),
     ('Roots and Ruins', 'Paula Kent', 2000, 'Historical Fiction', 344, 'A family estate torn by revolution.'),
     ('Static Bloom', 'Erica Mars', 2017, 'Cyberpunk', 359, 'Love in the heart of a neon dystopia.'),
     ('The Oracle''s Debt', 'Maxine Drake', 2018, 'Fantasy', 387, 'A prophecy demands blood and betrayal.'),
     ('Salt in the Wind', 'Noah Greene', 2009, 'Drama', 248, 'Healing by the sea after loss.'),
     ('When We Were Tomorrow', 'Clara Frost', 2016, 'Romance', 233, 'A second chance in a parallel life.'),
     ('Lanterns of the Deep', 'Miles Byrne', 2012, 'Adventure', 366, 'Ancient lights guide a sunken expedition.'),
     ('The Quiet Conductor', 'Felix Shaw', 2004, 'Mystery', 298, 'A murder on the last midnight train.'),
     ('Mirror of Shadows', 'Lena Vale', 2020, 'Fantasy', 360, 'Reflections reveal more than just the truth.'),
     ('Tanglewood Pact', 'Wes Harper', 2011, 'Fantasy', 351, 'Warring clans bound by a magical treaty.'),
     ('Bloodlines of Dust', 'Serena Cross', 2008, 'Fantasy', 328, 'Dynasties fall when old magic rises.'),
     ('Eclipsed Truth', 'Joel Banner', 2013, 'Sci-Fi', 317, 'Truth is a casualty in galactic war.'),
     ('The Forgotten Flame', 'Rita Dale', 2010, 'Fantasy', 342, 'A relic lights the way to redemption.');
